name: Deploy to production

on:
  workflow_run:
    workflows: ["Build from push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-from-artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          name: "site-build"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dwhswenson/static-site-workflow/actions/upload-site@main
        with:
          aws-region: us-east-2
          aws-role: ${{ secrets.PROD_ROLE }}
          bucket-name: ${{ secrets.PROD_BUCKET }}
          cloudfront-distribution: ${{ secrets.PROD_CLOUDFRONT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

